language: java
sudo: false
services:
  - docker
jdk:
- oraclejdk8
notifications:
  email:
  - philippe.granet@gmail.com
branches: 
only:
- master
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
install: true
jobs:
  include:
    - stage: Build
      script:
        - |
          mvn -B -V clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=philippe-granet-github \
            -Dsonar.login=$SONAR_LOGIN