version: '2.1'
services:
  just-ask-hub:
    build: .
    restart: always
    ports:
      - 4444:4444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    mem_limit: 256m
    environment:
      - TZ=Europe/Paris
      - GRID_TIMEOUT=1800
