version: '2.2'
services:
  just-ask-hub:
    build: .
    image: just-ask/hub
    restart: always
    init: true
    ports:
      - 4444:4444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    mem_limit: 256m
    environment:
      - TZ=Europe/Paris
      - GRID_TIMEOUT=1800
      - JAVA_OPTS=-Dselenium.LOGGER.level=INFO -Djust-ask.LOGGER.level=WARNING
