#!/bin/bash

cat <<_EOF
{
  "host": null,
  "port": 4444,
  "role": "hub",
  "maxSession": $GRID_MAX_SESSION,
  "newSessionWaitTimeout": $GRID_NEW_SESSION_WAIT_TIMEOUT,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": $GRID_THROW_ON_CAPABILITY_NOT_PRESENT,
  "jettyMaxThreads": $GRID_JETTY_MAX_THREADS,
  "cleanUpCycle": $GRID_CLEAN_UP_CYCLE,
  "browserTimeout": $GRID_BROWSER_TIMEOUT,
  "timeout": $GRID_TIMEOUT,
  "debug": $GRID_DEBUG,
  "servlets": [
    "com.rationaleemotions.servlets.JustAskServlet"
  ],
  "withoutServlets": [
  ],
  "justAsk": {
    "dockerRestApiUri": "unix:///var/run/docker.sock",
    "localhost": "0.0.0.0",
    "maxSession": $GRID_MAX_SESSION,
    "browsers": [
      {
        "browser": "chrome",
        "defaultVersion": "60.0.3112.113",
        "versions": [
          {
            "version": "58.0.3029.81",
            "implementation": "com.rationaleemotions.server.DockerBasedSeleniumServer",
            "target": {
              "image": "selenium/standalone-chrome:3.4.0-chromium",
              "port": "4444",
              "volumes": [
                "/dev/shm:/dev/shm"
              ],
              "env": [
                "JAVA_OPTS=-Xmx512m",
                "TZ=${TZ}",
                "SCREEN_WIDTH=1360",
                "SCREEN_HEIGHT=1020",
                "SCREEN_DEPTH=24"
              ]
            }
          },
          {
            "version": "59.0.3071.115",
            "implementation": "com.rationaleemotions.server.DockerBasedSeleniumServer",
            "target": {
              "image": "selenium/standalone-chrome:3.4.0-einsteinium",
              "port": "4444",
              "volumes": [
                "/dev/shm:/dev/shm"
              ],
              "env": [
                "JAVA_OPTS=-Xmx512m",
                "TZ=${TZ}",
                "SCREEN_WIDTH=1360",
                "SCREEN_HEIGHT=1020",
                "SCREEN_DEPTH=24"
              ]
            }
          },
          {
            "version": "60.0.3112.113",
            "implementation": "com.rationaleemotions.server.DockerBasedSeleniumServer",
            "target": {
              "image": "selenium/standalone-chrome:3.5.2-antimony",
              "port": "4444",
              "volumes": [
                "/dev/shm:/dev/shm"
              ],
              "env": [
                "JAVA_OPTS=-Xmx512m",
                "TZ=${TZ}",
                "SCREEN_WIDTH=1360",
                "SCREEN_HEIGHT=1020",
                "SCREEN_DEPTH=24"
              ]
            }
          }
        ]
      },
      {
        "browser": "firefox",
        "defaultVersion": "55.0.3",
        "versions": [
          {
            "version": "52.0.2",
            "implementation": "com.rationaleemotions.server.DockerBasedSeleniumServer",
            "target": {
              "image": "selenium/standalone-firefox:3.4.0-actinium",
              "port": "4444",
              "volumes": [
                "/dev/shm:/dev/shm"
              ],
              "shmSize": "2g",
              "env": [
                "JAVA_OPTS=-Xmx512m",
                "TZ=${TZ}",
                "SCREEN_WIDTH=1360",
                "SCREEN_HEIGHT=1020",
                "SCREEN_DEPTH=24"
              ]
            }
          },
          {
            "version": "53.0",
            "implementation": "com.rationaleemotions.server.DockerBasedSeleniumServer",
            "target": {
              "image": "selenium/standalone-firefox:3.4.0-dysprosium",
              "port": "4444",
              "volumes": [
                "/dev/shm:/dev/shm"
              ],
              "shmSize": "2g",
              "env": [
                "JAVA_OPTS=-Xmx512m",
                "TZ=${TZ}",
                "SCREEN_WIDTH=1360",
                "SCREEN_HEIGHT=1020",
                "SCREEN_DEPTH=24"
              ]
            }
          },
          {
            "version": "54.0",
            "implementation": "com.rationaleemotions.server.DockerBasedSeleniumServer",
            "target": {
              "image": "selenium/standalone-firefox:3.4.0-einsteinium",
              "port": "4444",
              "volumes": [
                "/dev/shm:/dev/shm"
              ],
              "shmSize": "2g",
              "env": [
                "JAVA_OPTS=-Xmx512m",
                "TZ=${TZ}",
                "SCREEN_WIDTH=1360",
                "SCREEN_HEIGHT=1020",
                "SCREEN_DEPTH=24"
              ]
            }
          },
          {
            "version": "55.0.3",
            "implementation": "com.rationaleemotions.server.DockerBasedSeleniumServer",
            "target": {
              "image": "selenium/standalone-firefox:3.5.2-antimony",
              "port": "4444",
              "volumes": [
                "/dev/shm:/dev/shm"
              ],
              "shmSize": "2g",
              "env": [
                "JAVA_OPTS=-Xmx512m",
                "TZ=${TZ}",
                "SCREEN_WIDTH=1360",
                "SCREEN_HEIGHT=1020",
                "SCREEN_DEPTH=24"
              ]
            }
          }
        ]
      }
    ]
  }
}

_EOF
