#!/bin/bash

cat <<_EOF
{
  "host": null,
  "port": 4444,
  "role": "hub",
  "maxSession": $GRID_MAX_SESSION,
  "newSessionWaitTimeout": $GRID_NEW_SESSION_WAIT_TIMEOUT,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": $GRID_THROW_ON_CAPABILITY_NOT_PRESENT,
  "jettyMaxThreads": $GRID_JETTY_MAX_THREADS,
  "cleanUpCycle": $GRID_CLEAN_UP_CYCLE,
  "browserTimeout": $GRID_BROWSER_TIMEOUT,
  "timeout": $GRID_TIMEOUT,
  "debug": $GRID_DEBUG,
  "servlets": [
    "com.rationaleemotions.servlets.JustAskServlet",
    "com.rationaleemotions.servlets.HubRequestsProxyingServlet"
  ],
  "withoutServlets": [
  ],
  "justAsk": {
    "dockerRestApiUri": "unix:///var/run/docker.sock",
    "localhost": "0.0.0.0",
    "maxSession": $GRID_MAX_SESSION,
    "browsers": [
      {
        "browser": "chrome",
        "defaultVersion": "64.0.3282.140",
        "versions": [
          {
            "version": "64.0.3282.140",
            "implementation": "com.rationaleemotions.server.DockerBasedSeleniumServer",
            "target": {
              "image": "selenium/standalone-chrome${NODE_DEBUG_IMAGE}:3.9.1-actinium",
              "port": "4444",
              "volumes": [
                "/dev/shm:/dev/shm"
              ],
              "memory": "$NODE_MEMORY",
              "env": [
                "JAVA_OPTS=$(echo $NODE_JAVA_OPTS)",
                "TZ=${TZ}",
                "SCREEN_WIDTH=$SCREEN_WIDTH",
                "SCREEN_HEIGHT=$SCREEN_HEIGHT",
                "SCREEN_DEPTH=$SCREEN_DEPTH"
              ]
            }
          }
        ]
      },
      {
        "browser": "firefox",
        "defaultVersion": "58.0.1",
        "versions": [
          {
            "version": "58.0.1",
            "implementation": "com.rationaleemotions.server.DockerBasedSeleniumServer",
            "target": {
              "image": "selenium/standalone-firefox${NODE_DEBUG_IMAGE}:3.9.1-actinium",
              "port": "4444",
              "volumes": [
                "/dev/shm:/dev/shm"
              ],
              "shmSize": "2g",
              "memory": "$NODE_MEMORY",
              "env": [
                "JAVA_OPTS=$(echo $NODE_JAVA_OPTS)",
                "TZ=${TZ}",
                "SCREEN_WIDTH=$SCREEN_WIDTH",
                "SCREEN_HEIGHT=$SCREEN_HEIGHT",
                "SCREEN_DEPTH=$SCREEN_DEPTH"
              ]
            }
          }
        ]
      }
    ]
  }
}
_EOF
